### ISSUE TITLE
Local notification not working on iOS >=10

### ISSUE THREAD

**Issue by kamleshpra995** [almende/virtuele-memo#22]
This is working on android and IOS <10.

Here is the code: 
`	cordova.plugins.notification.local.registerPermission(function (str) {
					cordova.plugins.notification.local.schedule({
						id: 1,
						sound: null,
						title: message
					});
				});

`
Please let me know this will work on IOS 10+ or not and what is wrong in my code so that I can correct it.

Thanks

**Comment by mrquincle** [comment]
This has been a temporary gadget for an event in 2014. It has not been maintained. Please, feel free to clone the repos and make your own variant.
